### ISSUE TITLE
ENV variable: how to configure several variables for several environments

### ISSUE THREAD

**Issue by albertorizzi** [przemek-nowicki/node-express-template.ts#6]
I want to declare several files like development.env or production.env to define respectively variables for development and production. How could I make this? I read about only [this file](https://github.com/przemek-nowicki/node-express-template.ts/blob/master/.env.local) to declare variables. Thank you.

**Comment by przemek-nowicki** [comment]
@albertorizzi My assumption is that providing environment variables for Docker file on other environments than local one is done during the deployment process by the CI/CD tools. There are many options to choose from, such as Jenkins, but the one I am considering adding to NET.ts are the github actions https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps.". I will let you know as soon as I introduce them to the template. However, at this moment, you need to set them manually (see the code below), if you don't have any automation in place.

`docker run --rm -it -e NODE_ENV='production' -e API_KEY_TOKEN='token' -p 8080:8080 net.ts`

**Comment by przemek-nowicki** [comment]
@albertorizzi let me know if this answers your question; if so, I would like to close this issue.

**Comment by albertorizzi** [comment]
@przemek-nowicki yes, you can close, thank you. I don't use Docker, but npm and `cross-env` to run scripts that set and use environment variables

`cross-env NODE_ENV=development ts-node-dev --inspect=0.0.0.0:9229 --exit-child --respawn -r tsconfig-paths/register src/server.ts`
